FROM ubuntu:16.04

# Install dependencies.
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       python-software-properties \
       software-properties-common \
       sudo systemd wget git \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /usr/share/doc && rm -Rf /usr/share/man \
    && apt-get clean

# Install Ansible.
RUN add-apt-repository -y ppa:ansible/ansible \
  && apt-get update \
  && apt-get install -y --no-install-recommends \
     ansible \
  && rm -rf /var/lib/apt/lists/* \
  && rm -rf /usr/share/doc && rm -Rf /usr/share/man \
  && apt-get clean

# Workaround for upstart.
RUN rm -f /sbin/initctl \
  && wget -O /sbin/initctl https://raw.githubusercontent.com/ontic/ansible-role-test/master/docker/sbin/initctl \
  && chmod +x /sbin/initctl

# Install Ansible inventory file.
RUN mkdir -p /etc/ansible \
  && printf "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

# Set working directory.
WORKDIR /etc/ansible/roles/role_under_test