FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive
ARG APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1

# Install dependencies.
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       software-properties-common \
       sudo systemd gnupg xz-utils wget git python3-pip \
    && pip3 install ansible \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /usr/share/doc && rm -Rf /usr/share/man \
    && apt-get clean

# Workaround for upstart.
RUN rm -f /sbin/initctl \
  && wget -O /sbin/initctl https://raw.githubusercontent.com/ontic/ansible-role-test/master/docker/sbin/initctl \
  && chmod +x /sbin/initctl

# Install Ansible inventory file.
RUN mkdir -p /etc/ansible \
  && printf "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

# Set working directory.
WORKDIR /etc/ansible/roles/role_under_test
