FROM ubuntu:16.04

# Install dependencies.
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       python-software-properties \
       software-properties-common \
       sudo systemd wget \
    && rm -Rf /var/lib/apt/lists/* \
    && rm -Rf /usr/share/doc && rm -Rf /usr/share/man \
    && apt-get clean

# Install Ansible.
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       build-essential libffi-dev libssl-dev \
       python-pip python-dev python-setuptools python-wheel \
    && rm -rf /var/lib/apt/lists/* \
    && rm -Rf /usr/share/doc && rm -Rf /usr/share/man \
    && apt-get clean
RUN pip install ansible cryptography

# Workaround for upstart.
RUN rm -fr /sbin/initctl \
  && wget -O /sbin/initctl https://raw.githubusercontent.com/ontic/ansible-role-test/master/initctl \
  && chmod +x /sbin/initctl

# Install Ansible inventory file.
RUN mkdir -p /etc/ansible \
  && printf "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts